---
- hosts: home
  gather_facts: yes
  become: yes
  roles:
    - role: ansible-roles/kubernetes/k3s-ansible/prereq
    - role: ansible-roles/kubernetes/k3s-ansible/download
    - role: ansible-roles/kubernetes/k3s-ansible/raspberrypi
    - role: ansible-roles/kubernetes/k3s-ansible/master
