---
- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: ansible-roles/k3s-ansible/prereq
    - role: ansible-roles/kubernetes/k3s-prereq-append
#    - role: ansible-roles/k3s-ansible/airgap
    - role: ansible-roles/k3s-ansible/raspberrypi

- hosts: server
  become: yes
  roles:
    - role: ansible-roles/k3s-ansible/k3s_server

- hosts: agent
  become: yes
  roles:
    - role: ansible-roles/k3s-ansible/k3s_agent